# coding: utf-8
from sqlalchemy import Column, Integer, Numeric, String, TIMESTAMP, Unicode
from sqlalchemy.dialects.mssql.base import UNIQUEIDENTIFIER
from apps.databases.db_source import db


Base = db.Model
metadata = Base.metadata


def to_dict(self):
    return {c.name: getattr(self, c.name, None) for c in self.__table__.columns}

Base.to_dict = to_dict
Base.__bind_key__ = 'db_source'


class PUPurchaseArrival(Base):
    __tablename__ = 'PU_PurchaseArrival'

    id = Column(UNIQUEIDENTIFIER, primary_key=True)
    code = Column(Unicode(30), index=True)
    name = Column(Unicode(200))
    invoiceType = Column(UNIQUEIDENTIFIER)
    purchaseInvoiceNo = Column(Unicode(30))
    discountRate = Column(Numeric(28, 14))
    acceptDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    exchangeRate = Column(Numeric(28, 14))
    deliveryMode = Column(UNIQUEIDENTIFIER)
    acceptAddress = Column(Unicode(200))
    linkMan = Column(Unicode(50))
    linkTelphone = Column(Unicode(100))
    payDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    payType = Column(UNIQUEIDENTIFIER)
    origPaymentCashAmount = Column(Numeric(28, 14))
    paymentCashAmount = Column(Numeric(28, 14))
    origTotalTaxAmount = Column(Numeric(28, 14))
    totalTaxAmount = Column(Numeric(28, 14))
    origtotalAmount = Column(Numeric(28, 14))
    totalAmount = Column(Numeric(28, 14))
    isPriceCheck = Column(Integer)
    isReduceArrival = Column(Integer)
    isAutoGenerateInvoice = Column(Integer)
    isAutoGenerateInStock = Column(Integer)
    voucherState = Column(UNIQUEIDENTIFIER)
    memo = Column(Unicode(200))
    saleOrderCode = Column(Unicode(30))
    saleOrderId = Column(UNIQUEIDENTIFIER)
    inStockState = Column(UNIQUEIDENTIFIER)
    settleState = Column(UNIQUEIDENTIFIER)
    isNoArapBookkeeping = Column(Integer)
    isNoModify = Column(Unicode(1000))
    voucherdate = Column(String(19, u'Chinese_PRC_CI_AS'), index=True)
    maker = Column(Unicode(50))
    madedate = Column(String(19, u'Chinese_PRC_CI_AS'))
    auditor = Column(Unicode(50))
    makerid = Column(UNIQUEIDENTIFIER)
    auditorid = Column(UNIQUEIDENTIFIER)
    reviser = Column(Unicode(50))
    auditeddate = Column(String(19, u'Chinese_PRC_CI_AS'))
    iscarriedforwardout = Column(Integer)
    iscarriedforwardin = Column(Integer)
    ismodifiedcode = Column(Integer)
    docno = Column(Unicode(36))
    docclass = Column(Unicode(36))
    accountingperiod = Column(Integer)
    docid = Column(Unicode(36))
    accountingyear = Column(Integer)
    createdtime = Column(String(19, u'Chinese_PRC_CI_AS'), index=True)
    sequencenumber = Column(Integer)
    ts = Column(TIMESTAMP)
    updated = Column(String(19, u'Chinese_PRC_CI_AS'))
    updatedBy = Column(Unicode(32))
    idbusinesstype = Column(UNIQUEIDENTIFIER)
    idclerk = Column(UNIQUEIDENTIFIER, index=True)
    idcurrency = Column(UNIQUEIDENTIFIER)
    idpartner = Column(UNIQUEIDENTIFIER, index=True)
    iddepartment = Column(UNIQUEIDENTIFIER, index=True)
    idwarehouse = Column(UNIQUEIDENTIFIER, index=True)
    idrdstyle = Column(UNIQUEIDENTIFIER)
    idqualityclerk = Column(UNIQUEIDENTIFIER, index=True)
    idsourcevouchertype = Column(UNIQUEIDENTIFIER, index=True)
    priuserdefnvc1 = Column(Unicode(500))
    priuserdefdecm1 = Column(Numeric(28, 14))
    priuserdefnvc2 = Column(Unicode(500))
    priuserdefdecm2 = Column(Numeric(28, 14))
    priuserdefnvc3 = Column(Unicode(500))
    priuserdefdecm3 = Column(Numeric(28, 14))
    priuserdefnvc4 = Column(Unicode(500))
    priuserdefdecm4 = Column(Numeric(28, 14))
    priuserdefnvc5 = Column(Unicode(500))
    priuserdefdecm5 = Column(Numeric(28, 14))
    priuserdefnvc6 = Column(Unicode(500))
    priuserdefdecm6 = Column(Numeric(28, 14))
    pubuserdefnvc1 = Column(Unicode(500))
    pubuserdefdecm1 = Column(Numeric(28, 14))
    pubuserdefnvc2 = Column(Unicode(500))
    pubuserdefdecm2 = Column(Numeric(28, 14))
    pubuserdefnvc3 = Column(Unicode(500))
    pubuserdefdecm3 = Column(Numeric(28, 14))
    pubuserdefnvc4 = Column(Unicode(500))
    pubuserdefdecm4 = Column(Numeric(28, 14))
    pubuserdefnvc5 = Column(Unicode(500))
    pubuserdefdecm5 = Column(Numeric(28, 14))
    pubuserdefnvc6 = Column(Unicode(500))
    pubuserdefdecm6 = Column(Numeric(28, 14))
    origPaymentAmount = Column(Numeric(28, 14))
    paymentAmount = Column(Numeric(28, 14))
    sourceVoucherCode = Column(Unicode(30))
    sourceVoucherDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    idproject = Column(UNIQUEIDENTIFIER, index=True)
    IsBeforeSystemInuse = Column(Integer)
    idMarketingOrgan = Column(UNIQUEIDENTIFIER)
    changedate = Column(String(19, u'Chinese_PRC_CI_AS'))
    changer = Column(Unicode(50))
    changerid = Column(UNIQUEIDENTIFIER)
    PrintCount = Column(Integer)
    idCollaborateDownVoucherType = Column(UNIQUEIDENTIFIER)
    CollaborateState = Column(UNIQUEIDENTIFIER)
    idCollaborateDownDraftVoucher = Column(UNIQUEIDENTIFIER)
    idCollaborateUpVoucherType = Column(UNIQUEIDENTIFIER)
    idCollaborateUpVoucher = Column(UNIQUEIDENTIFIER)
    collaborateVoucherCode = Column(Unicode(30))
