# coding: utf-8
from sqlalchemy import Column, Index, Integer, Numeric, String, TIMESTAMP, Unicode
from sqlalchemy.dialects.mssql.base import UNIQUEIDENTIFIER
from apps.databases.db_source import source_db


Base = source_db.Model
metadata = Base.metadata


def to_dict(self):
    return {c.name: getattr(self, c.name, None) for c in self.__table__.columns}

Base.to_dict = to_dict
Base.__bind_key__ = 'db_source'


class PUPurchaseArrivalB(Base):
    __tablename__ = 'PU_PurchaseArrival_b'
    __table_args__ = (
        Index('index_PU_PurchaseArrival_b_idPurchaseArrivalDTO__taxAmount', 'idPurchaseArrivalDTO', 'taxAmount'),
        Index('index_PU_PurchaseArrival_b_idPurchaseArrivalDTO__origSettleAmount', 'idPurchaseArrivalDTO', 'origSettleAmount')
    )

    id = Column(UNIQUEIDENTIFIER, primary_key=True)
    code = Column(Unicode(30))
    name = Column(Unicode(200))
    taxFlag = Column(Integer)
    compositionQuantity = Column(Unicode(100))
    inventoryLocation = Column(Unicode(50))
    quantity = Column(Numeric(28, 14))
    origDiscountPrice = Column(Numeric(28, 14))
    quantity2 = Column(Numeric(28, 14))
    origDiscountPrice2 = Column(Numeric(28, 14))
    baseQuantity = Column(Numeric(28, 14))
    subQuantity = Column(Numeric(28, 14))
    unitExchangeRate = Column(Numeric(28, 14))
    origPrice = Column(Numeric(28, 14))
    price = Column(Numeric(28, 14))
    discountRate = Column(Numeric(28, 14))
    taxRate = Column(Numeric(28, 14))
    origTaxPrice = Column(Numeric(28, 14))
    origDiscountAmount = Column(Numeric(28, 14))
    origTax = Column(Numeric(28, 14))
    origTaxAmount = Column(Numeric(28, 14))
    origDiscount = Column(Numeric(28, 14))
    discountPrice = Column(Numeric(28, 14))
    discountPrice2 = Column(Numeric(28, 14))
    taxPrice = Column(Numeric(28, 14))
    discountAmount = Column(Numeric(28, 14))
    tax = Column(Numeric(28, 14))
    taxAmount = Column(Numeric(28, 14))
    discount = Column(Numeric(28, 14))
    acceptDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    isPresent = Column(Integer)
    sourceVoucherCode = Column(Unicode(50))
    sourceVoucherId = Column(UNIQUEIDENTIFIER)
    sourceVoucherDetailId = Column(UNIQUEIDENTIFIER, index=True)
    saleOrderCode = Column(Unicode(30))
    saleOrderId = Column(UNIQUEIDENTIFIER)
    saleOrderDetailId = Column(UNIQUEIDENTIFIER)
    totalInvoiceQuantity = Column(Numeric(28, 14))
    totalInvoiceQuantity2 = Column(Numeric(28, 14))
    totalInQuantity = Column(Numeric(28, 14))
    totalInQuantity2 = Column(Numeric(28, 14))
    totalSettleQuantity = Column(Numeric(28, 14))
    totalSettleQuantity2 = Column(Numeric(28, 14))
    totalReturnQuantity = Column(Numeric(28, 14))
    totalReturnQuantity2 = Column(Numeric(28, 14))
    totalReduceQuantity = Column(Numeric(28, 14))
    totalReduceQuantity2 = Column(Numeric(28, 14))
    origSettleAmount = Column(Numeric(28, 14))
    settleAmount = Column(Numeric(28, 14))
    batch = Column(Unicode(50))
    expiryDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    arrivalQuantity = Column(Numeric(28, 14))
    acceptanceQuantity = Column(Numeric(28, 14))
    arrivalQuantity2 = Column(Numeric(28, 14))
    acceptanceQuantity2 = Column(Numeric(28, 14))
    warehouseAdjustAmount = Column(Numeric(28, 14))
    purchaseAmount = Column(Numeric(28, 14))
    isNoModify = Column(Unicode(1000))
    basePrice = Column(Numeric(28, 14))
    baseDiscountPrice = Column(Numeric(28, 14))
    baseTaxPrice = Column(Numeric(28, 14))
    totalSettleTaxAmount = Column(Numeric(28, 14))
    receiveVoucherCode = Column(Unicode(50))
    receiveVoucherId = Column(UNIQUEIDENTIFIER, index=True)
    receiveVoucherDetailId = Column(UNIQUEIDENTIFIER)
    lastmodifiedfield = Column(Unicode(50))
    inventoryBarCode = Column(Unicode(200))
    partnerInventoryCode = Column(Unicode(50))
    availableQuantity = Column(Numeric(28, 14))
    existingQuantity = Column(Numeric(28, 14))
    createdtime = Column(String(19, u'Chinese_PRC_CI_AS'))
    sequencenumber = Column(Integer)
    ts = Column(TIMESTAMP)
    updated = Column(String(19, u'Chinese_PRC_CI_AS'), index=True)
    updatedBy = Column(Unicode(32))
    idPurchaseArrivalDTO = Column(UNIQUEIDENTIFIER, index=True)
    idsourcevouchertype = Column(UNIQUEIDENTIFIER, index=True)
    idwarehouse = Column(UNIQUEIDENTIFIER, index=True)
    idunit = Column(UNIQUEIDENTIFIER)
    idunit2 = Column(UNIQUEIDENTIFIER)
    idbaseunit = Column(UNIQUEIDENTIFIER)
    idsubunit = Column(UNIQUEIDENTIFIER)
    idinventory = Column(UNIQUEIDENTIFIER, index=True)
    freeItem0 = Column(Unicode(300))
    freeItem1 = Column(Unicode(300))
    freeItem2 = Column(Unicode(300))
    freeItem3 = Column(Unicode(300))
    freeItem4 = Column(Unicode(300))
    freeItem5 = Column(Unicode(300))
    freeItem6 = Column(Unicode(300))
    freeItem7 = Column(Unicode(300))
    freeItem8 = Column(Unicode(300))
    freeItem9 = Column(Unicode(300))
    priuserdefnvc1 = Column(Unicode(500))
    priuserdefdecm1 = Column(Numeric(28, 14))
    priuserdefnvc2 = Column(Unicode(500))
    priuserdefdecm2 = Column(Numeric(28, 14))
    priuserdefnvc3 = Column(Unicode(500))
    priuserdefdecm3 = Column(Numeric(28, 14))
    priuserdefnvc4 = Column(Unicode(500))
    priuserdefdecm4 = Column(Numeric(28, 14))
    pubuserdefnvc1 = Column(Unicode(500))
    pubuserdefdecm1 = Column(Numeric(28, 14))
    pubuserdefnvc2 = Column(Unicode(500))
    pubuserdefdecm2 = Column(Numeric(28, 14))
    pubuserdefnvc3 = Column(Unicode(500))
    pubuserdefdecm3 = Column(Numeric(28, 14))
    pubuserdefnvc4 = Column(Unicode(500))
    pubuserdefdecm4 = Column(Numeric(28, 14))
    totalSettleBaseQuantity = Column(Numeric(28, 14))
    totalSettleSubQuantity = Column(Numeric(28, 14))
    arrivalBaseQuantity = Column(Numeric(28, 14))
    arrivalSubQuantity = Column(Numeric(28, 14))
    purchaseOrderCode = Column(Unicode(30))
    partnerInventoryName = Column(Unicode(50))
    shrinkageQuantity = Column(Numeric(28, 14))
    shrinkageQuantity2 = Column(Numeric(28, 14))
    shrinkageBaseQuantity = Column(Numeric(28, 14))
    shrinkageSubQuantity = Column(Numeric(28, 14))
    cumInstockShrinkageQuantity = Column(Numeric(28, 14))
    cumInstockShrinkageQuantity2 = Column(Numeric(28, 14))
    cumInvoiceShrinkageQuantity = Column(Numeric(28, 14))
    cumInvoiceShrinkageQuantity2 = Column(Numeric(28, 14))
    cumReturnShrinkageQuantity = Column(Numeric(28, 14))
    cumReturnShrinkageQuantity2 = Column(Numeric(28, 14))
    cumReduceShrinkageQuantity = Column(Numeric(28, 14))
    cumReduceShrinkageQuantity2 = Column(Numeric(28, 14))
    origShrinkageQuantity = Column(Numeric(28, 14))
    origShrinkageQuantity2 = Column(Numeric(28, 14))
    cumAccountAmount = Column(Numeric(28, 14))
    purchaseOrderDetailID = Column(UNIQUEIDENTIFIER)
    idproject = Column(UNIQUEIDENTIFIER, index=True)
    islaborcost = Column(Integer)
    RetailPrice = Column(Numeric(28, 14))
    ProductionDate = Column(String(19, u'Chinese_PRC_CI_AS'))
