# coding: utf-8
from sqlalchemy import Column, Index, Integer, Numeric, String, TIMESTAMP, Unicode
from sqlalchemy.dialects.mssql.base import UNIQUEIDENTIFIER
from apps.databases.db_source import db


Base = db.Model
metadata = Base.metadata


def to_dict(self):
    return {c.name: getattr(self, c.name, None) for c in self.__table__.columns}

Base.to_dict = to_dict
Base.__bind_key__ = 'db_source'


class SASaleDelivery(Base):
    __tablename__ = 'SA_SaleDelivery'
    __table_args__ = (
        Index('Idx_SA_SaleDelivery_createdtime_voucherdate', 'createdtime', 'voucherdate', 'id', 'idcustomer', 'idsettleCustomer', 'iddepartment', 'idclerk', 'makerid'),
        Index('Index_2', 'isBeforeSystemInuse', 'id', 'code', 'origTaxAmount', 'voucherState', 'memo', 'voucherdate', 'maker', 'auditor', 'idcustomer', 'iddepartment', 'createdtime', 'idbusinesstype', 'ts', 'SourceVoucherCode', 'changer'),
        Index('_dta_index_SA_SaleDelivery_id_Code_VoucherDate_VoucherSate', 'id', 'voucherdate', 'voucherState', 'code')
    )

    id = Column(UNIQUEIDENTIFIER, primary_key=True)
    code = Column(Unicode(30), index=True)
    name = Column(Unicode(200))
    origCancelAmount = Column(Numeric(28, 14))
    origAmount = Column(Numeric(28, 14))
    amount = Column(Numeric(28, 14))
    origTaxAmount = Column(Numeric(28, 14))
    taxAmount = Column(Numeric(28, 14))
    voucherState = Column(UNIQUEIDENTIFIER)
    isCounteractDelivery = Column(Integer)
    invoiceType = Column(UNIQUEIDENTIFIER)
    discountAmount = Column(Numeric(28, 14))
    discountRate = Column(Numeric(28, 14))
    discountsAndAllowances = Column(Numeric(28, 14))
    exchangeRate = Column(Numeric(28, 14))
    deliveryDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    deliveryMode = Column(UNIQUEIDENTIFIER)
    address = Column(Unicode(200))
    linkMan = Column(Unicode(50))
    reciveType = Column(UNIQUEIDENTIFIER)
    isCancel = Column(UNIQUEIDENTIFIER)
    cancelAmount = Column(Numeric(28, 14))
    recivingMaturity = Column(String(19, u'Chinese_PRC_CI_AS'))
    isPriceTrace = Column(Integer)
    memo = Column(Unicode(200))
    saleInvoiceNo = Column(Unicode(30))
    isAutoGenerateInvoice = Column(Integer)
    saleInvoiceID = Column(UNIQUEIDENTIFIER)
    isAutoGenerateSaleOut = Column(Integer)
    origSettleAmount = Column(Numeric(28, 14))
    settleAmount = Column(Numeric(28, 14))
    contactPhone = Column(Unicode(100))
    isNoModify = Column(Unicode(1000))
    isSaleOut = Column(UNIQUEIDENTIFIER)
    isBeforeSystemInuse = Column(Integer)
    voucherdate = Column(String(19, u'Chinese_PRC_CI_AS'), index=True)
    maker = Column(Unicode(50))
    madedate = Column(String(19, u'Chinese_PRC_CI_AS'))
    auditor = Column(Unicode(50))
    idcustomer = Column(UNIQUEIDENTIFIER, index=True)
    makerid = Column(UNIQUEIDENTIFIER)
    auditorid = Column(UNIQUEIDENTIFIER)
    reviser = Column(Unicode(50))
    idcurrency = Column(UNIQUEIDENTIFIER, index=True)
    auditeddate = Column(String(19, u'Chinese_PRC_CI_AS'))
    iddepartment = Column(UNIQUEIDENTIFIER, index=True)
    iscarriedforwardout = Column(Integer)
    iscarriedforwardin = Column(Integer)
    ismodifiedcode = Column(Integer)
    idclerk = Column(UNIQUEIDENTIFIER, index=True)
    docno = Column(Unicode(36))
    docclass = Column(Unicode(36))
    idwarehouse = Column(UNIQUEIDENTIFIER, index=True)
    accountingperiod = Column(Integer)
    docid = Column(Unicode(36))
    idrdstyle = Column(UNIQUEIDENTIFIER)
    accountingyear = Column(Integer)
    createdtime = Column(String(19, u'Chinese_PRC_CI_AS'), index=True)
    idbusinesstype = Column(UNIQUEIDENTIFIER)
    sequencenumber = Column(Integer)
    ts = Column(TIMESTAMP)
    updated = Column(String(19, u'Chinese_PRC_CI_AS'))
    updatedBy = Column(Unicode(32))
    idsourcevouchertype = Column(UNIQUEIDENTIFIER, index=True)
    priuserdefnvc1 = Column(Unicode(500))
    priuserdefdecm1 = Column(Numeric(28, 14))
    priuserdefnvc2 = Column(Unicode(500))
    priuserdefdecm2 = Column(Numeric(28, 14))
    priuserdefnvc3 = Column(Unicode(500))
    priuserdefdecm3 = Column(Numeric(28, 14))
    priuserdefnvc4 = Column(Unicode(500))
    priuserdefdecm4 = Column(Numeric(28, 14))
    priuserdefnvc5 = Column(Unicode(500))
    priuserdefdecm5 = Column(Numeric(28, 14))
    priuserdefnvc6 = Column(Unicode(500))
    priuserdefdecm6 = Column(Numeric(28, 14))
    pubuserdefnvc1 = Column(Unicode(500))
    pubuserdefdecm1 = Column(Numeric(28, 14))
    pubuserdefnvc2 = Column(Unicode(500))
    pubuserdefdecm2 = Column(Numeric(28, 14))
    pubuserdefnvc3 = Column(Unicode(500))
    pubuserdefdecm3 = Column(Numeric(28, 14))
    pubuserdefnvc4 = Column(Unicode(500))
    pubuserdefdecm4 = Column(Numeric(28, 14))
    pubuserdefnvc5 = Column(Unicode(500))
    pubuserdefdecm5 = Column(Numeric(28, 14))
    pubuserdefnvc6 = Column(Unicode(500))
    pubuserdefdecm6 = Column(Numeric(28, 14))
    isNoArapBookkeeping = Column(Integer)
    origprereceiveamount = Column(Numeric(28, 14))
    PreReceiveAmount = Column(Numeric(28, 14))
    ReceiveBalance = Column(Numeric(28, 14))
    SourceVoucherCode = Column(Unicode(50))
    SourceVoucherDate = Column(String(19, u'Chinese_PRC_CI_AS'))
    idsettleCustomer = Column(UNIQUEIDENTIFIER, index=True)
    idproject = Column(UNIQUEIDENTIFIER, index=True)
    idmarketingOrgan = Column(UNIQUEIDENTIFIER, index=True)
    changedate = Column(String(19, u'Chinese_PRC_CI_AS'))
    changer = Column(Unicode(50))
    changerid = Column(UNIQUEIDENTIFIER)
    DataSource = Column(UNIQUEIDENTIFIER)
    OrigInvoiceTaxAmount = Column(Numeric(28, 14))
    IdMember = Column(UNIQUEIDENTIFIER)
    thisBalanceIntegral = Column(Integer)
    Mobilephone = Column(String(20, u'Chinese_PRC_CI_AS'))
    MemberAddress = Column(String(50, u'Chinese_PRC_CI_AS'))
    PrintCount = Column(Integer)
    idCollaborateUpVoucherType = Column(UNIQUEIDENTIFIER)
    idCollaborateUpVoucher = Column(UNIQUEIDENTIFIER)
    IsSeparateByWareHouse = Column(Integer)
    Allowances = Column(Numeric(28, 14))
    origAllowances = Column(Numeric(28, 14))
    IsAutoSaleOut = Column(Integer)
    ExternalCode = Column(Unicode(50))
    idCollaborateDownVoucherType = Column(UNIQUEIDENTIFIER)
    CollaborateState = Column(UNIQUEIDENTIFIER)
    idCollaborateDownDraftVoucher = Column(UNIQUEIDENTIFIER)
    collaborateVoucherCode = Column(Unicode(30))
